on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]

name: Test GitHub Action Conversion

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
